(bin,shell) modified remaps, and added script to switch displays

diff --git a/.local/bin/dmenu_mount b/.local/bin/dmenu_mount
--- a/.local/bin/dmenu_mount
+++ b/.local/bin/dmenu_mount
@@ -1,64 +1,110 @@
-#!/bin/sh
+#!/bin/bash
 
 # script that generates a front-end for mount
 
-getmount() { \
-	[ -z "$chosen" ] && exit 1
-        # shellcheck disable=SC2086
-	mp="$(find $1 2>/dev/null | dmenu -p "Type in mount point.")" || exit 1
-	test -z "$mp" && exit 1
+IFS='
+'
+# Function for escaping cell-phone names.
+escape(){ echo "$@" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g" ;}
+
+# Check for phones.
+phones="$(simple-mtpfs -l 2>/dev/null | sed "s/^/󰄜/")"
+mountedphones="$(grep "simple-mtpfs" /etc/mtab)"
+# If there are already mounted phones, remove them from the list of mountables.
+[ -n "$mountedphones" ] && phones="$(for phone in $phones; do
+	for mounted in $mountedphones; do
+		escphone="$(escape "$phone")"
+		[[ "$mounted" =~ "$escphone" ]] && break 1
+	done && continue 1
+	echo "$phone"
+done)"
+
+# Check for drives.
+lsblkoutput="$(lsblk -rpo "uuid,name,type,size,label,mountpoint,fstype")"
+# Get all LUKS drives
+allluks="$(echo "$lsblkoutput" | grep crypto_LUKS)"
+# Get a list of the LUKS drive UUIDs already decrypted.
+decrypted="$(find /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-* | sed "s|.*LUKS2-||;s|-.*||")"
+# Functioning for formatting drives correctly for dmenu:
+filter() { sed "s/ /:/g" | awk -F':' '$7==""{printf "%s%s (%s) %s\n",$1,$3,$5,$6}' ; }
+
+# Get only LUKS drives that are not decrypted.
+unopenedluks="$(for drive in $allluks; do
+	uuid="${drive%% *}"
+	uuid="${uuid//-}"	# This is a bashism.
+	for open in $decrypted; do
+		[ "$uuid" = "$open" ] && break 1
+	done && continue 1
+	echo "󰌾 $drive"
+done | filter)"
+
+# Get all normal, non-encrypted or decrypted partitions that are not mounted.
+normalparts="$(echo "$lsblkoutput"| grep -v crypto_LUKS | grep 'part\|rom\|crypt' | sed "s/^/󰕓 /" | filter )"
+
+# Add all to one variable. If no mountable drives found, exit.
+alldrives="$(echo "$phones
+$unopenedluks
+$normalparts" | sed "/^$/d;s/ *$//")"
+
+# Quit the script if a sequential command fails.
+set -e
+
+test -n "$alldrives"
+
+# Feed all found drives to dmenu and get user choice.
+chosen="$(echo "$alldrives" | dmenu -p "Mount which drive?" -i)"
+
+# Function for prompting user for a mountpoint.
+getmount(){
+	mp="$(find /mnt /media /mount /home -maxdepth 1 -type d 2>/dev/null | dmenu -i -p "Mount this drive where?")"
+	test -n "$mp"
 	if [ ! -d "$mp" ]; then
-		mkdiryn=$(printf "No\\nYes" | dmenu -p "$mp does not exist. Create it?") || exit 1
+		mkdiryn=$(printf "No\\nYes" | dmenu -i -p "$mp does not exist. Create it?")
 		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
 	fi
-	}
+}
 
-mountusb() { \
-	chosen="$(echo "$usbdrives" | dmenu -p "Mount which drive?")" || exit 1
-	chosen="$(echo "$chosen" | awk '{print $1}')"
-	sudo -A mount "$chosen" 2>/dev/null && notify-send "󰕓 USB mounting" "$chosen mounted." && exit 0
-	alreadymounted=$(lsblk -nrpo "name,type,mountpoint" | awk '$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "-not ( -path *%s -prune ) ",$3}')
-	getmount "/mnt /media /mount /home -maxdepth 5 -type d $alreadymounted"
-	partitiontype="$(lsblk -no "fstype" "$chosen")"
-	case "$partitiontype" in
-		"vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
-		"exfat") sudo -A mount "$chosen" "$mp" -o uid="$(id -u)",gid="$(id -g)";;
-		*) sudo -A mount "$chosen" "$mp"; user="$(whoami)"; ug="$(groups | awk '{print $1}')"; sudo -A chown "$user":"$ug" "$mp";;
-	esac
-	notify-send "💻 USB mounting" "$chosen mounted to $mp."
-	}
+attemptmount(){
+		# Attempt to mount without a mountpoint, to see if drive is in fstab.
+		sudo -A mount "$chosen" || return 1
+		notify-send "󰕓 Drive mounting" "$chosen mounted."
+		exit
+}
 
-mountandroid() { \
-	chosen="$(echo "$anddrives" | dmenu -p "Which Android device?")" || exit 1
-	chosen="$(echo "$chosen" | cut -d : -f 1)"
-	getmount "$HOME -maxdepth 3 -type d"
-        simple-mtpfs --device "$chosen" "$mp"
-	echo "OK" | dmenu -p "Tap Allow on your phone if it asks for permission and then press enter" || exit 1
-	simple-mtpfs --device "$chosen" "$mp"
-	notify-send "🤖 Android Mounting" "Android device mounted to $mp."
-	}
+case "$chosen" in
+  󰕓*)
+		chosen="${chosen%% *}"
+		chosen="${chosen:1}"	# This is a bashism.
+		attemptmount || getmount
+		sudo -A mount "$chosen" "$mp" -o uid="$(id -u)",gid="$(id -g)"
+		notify-send "💻 Drive mounting" "$chosen mounted to $mp."
+		;;
 
-asktype() { \
-	choice="$(printf "USB\\nAndroid" | dmenu -p "Mount a USB drive or Android device?")" || exit 1
-	case $choice in
-		USB) mountusb ;;
-		Android) mountandroid ;;
-	esac
-	}
+	󰌾*)
+		chosen="${chosen%% *}"
+		chosen="${chosen:1}"	# This is a bashism.
+		# Number the drive.
+		while true; do
+			[ -f "/dev/mapper/usb$num" ] || break
+			num="$(printf "%02d" "$((num +1))")"
+		done
 
-anddrives=$(simple-mtpfs -l 2>/dev/null)
-usbdrives="$(lsblk -rpo "name,type,size,label,mountpoint,fstype" | grep -v crypto_LUKS | grep 'part\|rom' | sed 's/ /:/g' | awk -F':' '$5==""{printf "%s (%s) %s\n",$1,$3,$4}')"
+		# Decrypt in a terminal window
+		${TERMINAL:-st} -n floatterm -g 60x1 -e sudo cryptsetup open "$chosen" "usb$num"
+		# Check if now decrypted.
+		test -b "/dev/mapper/usb$num"
 
-if [ -z "$usbdrives" ]; then
-	[ -z "$anddrives" ] && echo "No USB drive or Android device detected" && exit
-	echo "Android device(s) detected."
-	mountandroid
-else
-	if [ -z "$anddrives" ]; then
-		echo "USB drive(s) detected."
-		mountusb
-	else
-		echo "Mountable USB drive(s) and Android device(s) detected."
-		asktype
-	fi
-fi
+		attemptmount || getmount
+		sudo -A mount "/dev/mapper/usb$num" "$mp" -o uid="$(id -u)",gid="$(id -g)"
+		notify-send "󰌿 Decrypted drive mounted." "$chosen decrypted and mounted to $mp."
+		;;
+
+	󰄜*)
+		notify-send "󱈸 Note" "Remember to allow file access on your phone now."
+		getmount
+		number="${chosen%%:*}"
+		number="${chosen:1}"	# This is a bashism.
+		sudo -A simple-mtpfs -o allow_other -o fsname="simple-mtpfs-$(escape "$chosen")" --device "$number" "$mp"
+		notify-send "󱟽 Phone mounted." "Phone mounted to $mp."
+		;;
+esac
diff --git a/.local/bin/dmenu_network b/.local/bin/dmenu_network
--- a/.local/bin/dmenu_network
+++ b/.local/bin/dmenu_network
@@ -2,49 +2,55 @@
 
 # script that generates a front-end for iwctl
 
+# Display help
+display_help() {
+  cat << EOF
+
+Usage: dmenu_network [options] <SSID>
+
+Description:
+  A front-end for iwctl using dmenu.
+
+Commands:
+  --help                   Display this help page.
+  --connect <SSID>         Connect to a specified or chosen Wi-Fi network.
+  --disconnect             Disconnect from the current Wi-Fi network.
+  --forget <SSID>          Forget a specified network.
+  --reset                  Bring Wi-Fi interface down, then up again (requires sudo permissions).
+
+EOF
+  exit 0
+}
+
 # Check for valid parameters
 if [[ ! -z $1 ]];
 then
-	case $1 in 
-		help | connect | disconnect | forget | reset )
-		;;
-		*)
-			echo "Invalid parameter $1"
-			echo "Use 'wifi help' for more info"
-			exit 1
-		;;
-	esac
+  case $1 in 
+    --help | --connect | --disconnect | --forget | --reset )
+    ;;
+      *)
+        echo "Invalid command $1"
+        echo "Use 'dmenu_network --help' for more info."
+        exit 1
+    ;;
+  esac
 fi
 
-# Display help
-if [[ $1 == "help" ]];
-then
-	printf "\n"
-	printf " wifi parameters\n"
-	printf "=================\n\n"
-	printf "wifi [connect] [SSID]\n"
-	printf "    Default parameter. Select and connect to a wifi network.\n\n"
-	printf "wifi disconnect\n"
-	printf "    Disconnect the current wifi connection.\n\n"
-	printf "wifi forget [SSID]\n"
-	printf "    Forget name and password of known network.\n\n"
-	printf "wifi reset\n"
-	printf "    Bring wifi interface down, then up again. User requires 'sudo' permissions.\n\n"
-	exit 0
-fi
-	
+# Check help parameter and display help
+[[ $1 == "--help" ]] && display_help	
+
 # Check if iwd is installed first
 if ! command -v iwctl &> /dev/null
 then
-	notify-send "Network" "󰀦 Could not find command 'iwctl'"
-	exit 1
+  notify-send "Network" "󰀦 Could not find command 'iwctl'"
+  exit 1
 fi
 
 # Check if iwd service is running
 if [[ "inactive" == $(systemctl is-active iwd.service) ]]
 then
-	notify-send "Network" "󰲝 Attempting to start 'iwd.service'..."
-	$(sudo -A systemctl start iwd.service) || exit 1
+  notify-send "Network" "󰲝 Attempting to start 'iwd.service'..."
+  $(sudo -A systemctl start iwd.service) || exit 1
 fi
 
 # Forget selected wifi network
@@ -176,7 +182,7 @@ then
 	# Trim selected network for SSID
 	WIFI_NETWORK=$(
 		echo "$WIFI_NETWORK_LIST" |
-		dmenu -p "$WIFI_DEVICE: Select wifi network" -l 30 | 
+		dmenu -p "Select Wi-Fi network:" -l 30 | 
 		sed 's/ *\(psk\|open\|8021x\) \+\*\+//g' | 
 		sed 's/^ *>\? *//g' | 
 		sed 's/ *$//g'
@@ -190,7 +196,7 @@ fi
 
 # Connect to wifi
 # This command will prompt for password first if required
-WIFI_PASSWORD=$(echo "" | dmenu -P -p "Enter Password 󰟵 :")
+WIFI_PASSWORD=$(echo "" | dmenu -P -p "Enter password 󰟵 :")
 iwctl --passphrase="$WIFI_PASSWORD" station "$WIFI_DEVICE" connect "$WIFI_NETWORK" &&
 notify-send "Network" "󰱓 Connected to $WIFI_NETWORK"  ||
 notify-send "Network" "󰲜 Could not connect to $WIFI_NETWORK"
