(bin/newsboat) added lf scripts for image preview, updated feeds

diff --git a/.local/bin/getpaper b/.local/bin/getpaper
--- a/.local/bin/getpaper
+++ b/.local/bin/getpaper
@@ -1,68 +1,92 @@
-#!/bin/sh
+#!/bin/bash
 
-TMP_HTML="/tmp/get_article_html"
-
-usage(){
-  	echo "Usage: ${0} [-hv] [-o OUTPUT] DOI"
-  	echo "Get an article from sci-hub with its DOI."
-  	echo "  -o OUTPUT	Output file name"
-  	echo "  -h			Prints usage."
-  	echo "  -v			Verbose output."
+# Function to pull the filename from the target
+# We use this for defining the saved filename
+extract_filename() {
+  local start_pos
+  start_pos=$(awk -F"/" '{print length($0)-length($NF)}' <<< "${1:?Null string}")
+  printf -- '%s\n' "${1:start_pos}"
 }
 
-get_pdf(){
-	wget -O ${TMP_HTML} "https://sci-hub.se/${DOI}"
-	PDF_URL="$(cat ${TMP_HTML} | grep -A1 '<div id="article">' | tail -n 1 | awk -F 'src="' '{print $NF}' | awk -F '#' '{print $1}')"
-	if [[ $PDF_URL == "" ]]
-	then
-		echo "Couln't find the article. Please check DOI and try again." >&2
-		exit 1
-	fi
-	if [[ ${OUTPUT} != "" ]]
-	then
-		wget -O ${OUTPUT} "${PDF_URL}"
-	else
-		wget "${PDF_URL}"
-	fi
+# Function to extract download target from sci-hub html
+get_target() {
+  printf -- '%s' "https:"
+  curl -s https://sci-hub.se/"${1:?No target specified}" | 
+    grep location.href |
+    grep -Eo '//[^ ]+pdf'
 }
 
-error_exit(){
-	echo "$1" >&2
-	usage >&2
+# Download our target via tor
+get_url_via_tor() {
+  # Ensure that Tor is running
+  if ! systemctl is-active --quiet tor; then
+    printf -- '%s\n' "Tor is not running yet: Starting Tor"
+    if ! systemctl start tor; then
+      printf -- '%s\n' /
+        "An error occured while initializing Tor"
+        "Make sure to correct this error, fix it and try again"
+    fi
+  fi
+  target_url="$(proxychains -q get_target "${1}")"
+  printf -- '%s\n' "${target_url}"
+  proxychains -q curl "${target_url}" -o "$(extract_filename "${target_url}")"
+  printf -- '%s\n' /
+    "Saved as $(extract_filename "${target_url}")"
+    "Once you are done do not forget to turn off Tor :)"
+}
+
+# Download our target
+get_url() {
+  target_url=$(get_target "${1}")
+  printf -- '%s\n' "${target_url}"
+  curl "${target_url}" -o "$(extract_filename "${target_url}")"
+  printf -- '%s\n' "Saved as $(extract_filename "${target_url}")"
+}
+
+# Usage function
+# This is exempt from our indentation rules as it's a heredoc
+print_usage() {
+cat <<USAGE
+Usage: scihub [-h|--help|-t|--tor] [url]
+
+Options:
+    -h | --help    This usage message.
+    -t | --tor     Attempt to fetch via tor network
+
+Examples:
+    scihub https://academic.oup.com/jn/article/130/4/1049S/4686675
+    scihub --tor https://academic.oup.com/jn/article/130/4/1049S/4686675
+USAGE
+  return 0
+}
+
+# Go interactive and get the url from the user if required
+read_url() {
+  read -rp 'url: ' input_url
+}
+
+# Ensure that the given url actually works, fail out if it doesn't
+validate_url() {
+  if ! curl --output /dev/null -s --head --fail "${1:?No URL supplied}"; then
+    printf -- '%s\n' "url: '${1}' not accesible, aborting"
     exit 1
+  fi
 }
 
-while getopts ho:v OPTION
-do
-	case ${OPTION} in
-		v)
-			VERBOSE="true"
-			;;
-		h)
-			usage
-			exit 0
-			;;
-		o)
-			OUTPUT="${OPTARG}"
-			;;
-		?)
-			error_exit "Invalid argument or option." >&2
-			;;
-	esac
-done
-
-shift "$(( OPTIND - 1 ))"
-
-[[ "${#}" -gt 1 ]] && error_exit "Too many arguments."
-[[ "${#}" -lt 1 ]] && error_exit "No DOI given."
-
-DOI="$1"
-
-if [[ $VERBOSE == "true" ]]
-then
-	get_pdf
-else
-	get_pdf &>/dev/null
-fi
-
-exit 0
+# Do the things
+case "${1}" in
+  (-t|--tor)
+    shift
+    # If no url is given, go interactive
+    [[ -z "${1}" ]] && read_url
+    validate_url "${1:-$input_url}"
+    printf -- '%s\n' "Getting resource via Tor service"
+    get_url_via_tor "${1:-$input_url}"
+  ;;
+  (-h|--help|-?|--*) print_usage ;;
+  (''|*)
+    [[ -z "${1}" ]] && read_url
+    validate_url "${1:-$input_url}"
+    get_url "${1:-$input_url}"
+  ;;
+esac
